# Generated by Django 3.2 on 2021-05-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fs_account',
            name='account_detail',
            field=models.CharField(blank=True, help_text='계정상세', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fs_account',
            name='account_amount',
            field=models.FloatField(blank=True, help_text='계정명에 대한 자산', null=True),
        ),
    ]
