# Generated by Django 3.2 on 2021-05-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantDB', '0003_company_market_capitalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='market_capitalization',
        ),
        migrations.AddField(
            model_name='company',
            name='short_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Corpdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_cap', models.IntegerField(blank=True, help_text='시가총액', null=True)),
                ('per', models.FloatField(blank=True, help_text='PER', null=True)),
                ('pbr', models.FloatField(blank=True, help_text='PBR', null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantDB.company')),
            ],
            options={
                'verbose_name': '일별 데이터',
                'verbose_name_plural': '일별 데이터',
            },
        ),
    ]
