export const rankConstants = {
  GET: 'rank/GET',

  SHOWCONDITION: 'rank/SHOWCONDITION',
  SHOWRANKCONDITION: 'rank/SHOWRANKCONDITION',

  CLOSECONDITION: 'rank/CANCLECONDITION',
  CLOSERANKCONDITION: 'rank/CLOASERANKCONDIDTION',

  ADDCONDITION: 'rank/ADDCONDITION',
  ADDRANKCONDITION: 'rank/ADDRANKCONDITION',

  DELETECONDITION: 'rank/DELETECONDITION',
  DELETERANKCONDITION: 'rank/DELETERANKCONDITION'

}
