export const userConstants = {
  // 회원가입
  REGISTER_REQUEST: 'user/USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'user/USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'user/USERS_REGISTER_FAILURE',
  // 로그인
  LOGIN_REQUEST: 'user/USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'user/USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'user/USERS_LOGIN_FAILURE',
  // 로그아웃
  LOGOUT: 'user/USERS_LOGOUT',
  // 유저 정보 가져오기
  GETALL_REQUEST: 'user/USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'user/USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'user/USERS_GETALL_FAILURE',
  // 회원탈퇴
  DELETE_REQUEST: 'user/USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'user/USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'user/USERS_DELETE_FAILURE'    
};