# Generated by Django 3.2.8 on 2021-11-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_company',
        ),
    ]
