version: "3.3"
services:
  nginx:
    image: nginx:1.21.1
    networks:
      - quant
    volumes:
      - ${PWD}/localnginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on: 
      - quant_home
      - quant_crawling
  
  quant_home:
    image: quant_home:0.2
    networks:
      - quant
    volumes:
      - /home/ubuntu/Quant_Project/server:/home/ubuntu/quant_server
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["bash", "-c"]
    command: 
      - |
        python manage.py makemigrations --settings=config.settings.local
        python manage.py migrate --settings=config.settings.local
        python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local
  
  quant_crawling:
    image: quant_home:0.2
    networks:
      - quant
    volumes:
      - /home/ubuntu/Quant_Project/server:/home/ubuntu/quant_server
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["bash", "-c"]
    command: 
      - |
        python manage.py makemigrations --settings=config.settings.local
        python manage.py migrate --settings=config.settings.local
        python manage.py runserver 0.0.0.0:8080 --settings=config.settings.local

networks:
  quant: