# Generated by Django 3.2 on 2021-05-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '기업',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Dart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dart_code', models.CharField(blank=True, help_text='고유번호', max_length=10, null=True)),
                ('company_name_dart', models.CharField(blank=True, help_text='회사명', max_length=50, null=True)),
                ('short_code', models.CharField(blank=True, help_text='종목코드', max_length=30, null=True)),
                ('recent_modify', models.CharField(blank=True, help_text='최종변경일자', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'dart 정보',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_year', models.IntegerField(blank=True, help_text='사업연도', null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantDB.company')),
            ],
            options={
                'verbose_name': '연도별 데이터',
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_name', models.CharField(blank=True, help_text='분기', max_length=30, null=True)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantDB.year')),
            ],
            options={
                'verbose_name': '분기별 데이터',
            },
        ),
        migrations.CreateModel(
            name='FS_LoB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lob', models.CharField(blank=True, help_text='연결/일반', max_length=30, null=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantDB.quarter')),
            ],
            options={
                'verbose_name': '연결/일반',
            },
        ),
        migrations.CreateModel(
            name='FS_Div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sj_div', models.CharField(blank=True, help_text='재무제표구분(BS IS ...)', max_length=255, null=True)),
                ('lob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantDB.fs_lob')),
            ],
            options={
                'verbose_name': '재무제표구분',
            },
        ),
        migrations.CreateModel(
            name='FS_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, help_text='계정명', max_length=255, null=True)),
                ('account_amount', models.IntegerField(blank=True, help_text='계정명에 대한 자산', null=True)),
                ('fs_div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantDB.fs_div')),
            ],
        ),
    ]
