# Generated by Django 3.1.3 on 2021-05-05 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '기업',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Financial_Statements_Div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sj_div', models.CharField(help_text='재무제표구분(BS IS ...)', max_length=255)),
            ],
            options={
                'verbose_name': '재무제표구분',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsns_year', models.IntegerField(blank=True, help_text='사업연도', null=True)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantDB.company')),
            ],
            options={
                'verbose_name': '연도별 데이터',
                'ordering': ['bsns_year'],
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_name', models.CharField(blank=True, help_text='분기', max_length=30, null=True)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantDB.year')),
            ],
            options={
                'verbose_name': '분기별 데이터',
            },
        ),
        migrations.CreateModel(
            name='FS_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='계정명', max_length=255)),
                ('a', models.IntegerField(blank=True, help_text='계정명에 대한 자산', null=True)),
                ('financial_statements_div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantDB.financial_statements_div')),
            ],
        ),
        migrations.CreateModel(
            name='Financial_Statements_LinkOrBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkOrbasic', models.CharField(blank=True, max_length=30, null=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantDB.quarter')),
            ],
            options={
                'verbose_name': '연결/기본',
            },
        ),
        migrations.AddField(
            model_name='financial_statements_div',
            name='lb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantDB.financial_statements_linkorbasic'),
        ),
    ]
