# Generated by Django 3.1.3 on 2021-05-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='company_name',
            new_name='company',
        ),
    ]
