# Generated by Django 3.2 on 2021-05-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique_code',
            name='dart_code',
            field=models.CharField(blank=True, help_text='고유번호', max_length=10, null=True),
        ),
    ]
