# Generated by Django 3.2 on 2021-09-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarter',
            name='ROA',
        ),
        migrations.RemoveField(
            model_name='quarter',
            name='ROE',
        ),
        migrations.AddField(
            model_name='fs_account',
            name='account_add_amount',
            field=models.FloatField(blank=True, help_text='계정명에 대한 누적 금액', null=True),
        ),
        migrations.AddField(
            model_name='sub_account',
            name='account_add_amount',
            field=models.FloatField(blank=True, help_text='계정명에 대한 누적 금액', null=True),
        ),
        migrations.AlterField(
            model_name='sub_account',
            name='account_amount',
            field=models.FloatField(blank=True, help_text='계정명에 대한 금액', null=True),
        ),
    ]
