# Generated by Django 3.2 on 2021-10-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0002_auto_20210923_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='fs_lob',
            name='ROA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fs_lob',
            name='ROE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
