# Generated by Django 3.2.8 on 2021-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0003_auto_20211117_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fs_lob',
            name='net_income',
            field=models.FloatField(blank=True, default=0, help_text='당기순이익(CIS)', null=True),
        ),
    ]
