# Generated by Django 3.2.8 on 2021-11-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0004_alter_fs_lob_net_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_price',
            name='cfs_pcr',
            field=models.FloatField(blank=True, help_text='CFS_PCR', null=True),
        ),
        migrations.AddField(
            model_name='daily_price',
            name='cfs_psr',
            field=models.FloatField(blank=True, help_text='CFS_PSR', null=True),
        ),
        migrations.AddField(
            model_name='daily_price',
            name='ofs_pcr',
            field=models.FloatField(blank=True, help_text='OFS_PCR', null=True),
        ),
        migrations.AddField(
            model_name='daily_price',
            name='ofs_psr',
            field=models.FloatField(blank=True, help_text='OFS_PSR', null=True),
        ),
        migrations.AlterField(
            model_name='daily_price',
            name='cfs_pbr',
            field=models.FloatField(blank=True, help_text='CFS_PBR', null=True),
        ),
        migrations.AlterField(
            model_name='daily_price',
            name='cfs_per',
            field=models.FloatField(blank=True, help_text='CFS_PER', null=True),
        ),
        migrations.AlterField(
            model_name='daily_price',
            name='ofs_pbr',
            field=models.FloatField(blank=True, help_text='OFS_PBR', null=True),
        ),
        migrations.AlterField(
            model_name='daily_price',
            name='ofs_per',
            field=models.FloatField(blank=True, help_text='OFS_PER', null=True),
        ),
    ]
