# Generated by Django 3.2.8 on 2021-11-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0005_auto_20211110_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='fs_lob',
            name='GPA',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
