# Generated by Django 3.2.8 on 2021-11-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0005_auto_20211119_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_price',
            name='cfs_pbr',
        ),
        migrations.RemoveField(
            model_name='daily_price',
            name='cfs_pcr',
        ),
        migrations.RemoveField(
            model_name='daily_price',
            name='cfs_per',
        ),
        migrations.RemoveField(
            model_name='daily_price',
            name='cfs_psr',
        ),
        migrations.RemoveField(
            model_name='daily_price',
            name='ofs_pbr',
        ),
        migrations.RemoveField(
            model_name='daily_price',
            name='ofs_pcr',
        ),
        migrations.RemoveField(
            model_name='daily_price',
            name='ofs_per',
        ),
        migrations.RemoveField(
            model_name='daily_price',
            name='ofs_psr',
        ),
        migrations.AddField(
            model_name='daily_price',
            name='bps',
            field=models.FloatField(blank=True, help_text='BPS', null=True),
        ),
        migrations.AddField(
            model_name='daily_price',
            name='div',
            field=models.FloatField(blank=True, help_text='DIV', null=True),
        ),
        migrations.AddField(
            model_name='daily_price',
            name='dps',
            field=models.FloatField(blank=True, help_text='DPS', null=True),
        ),
        migrations.AddField(
            model_name='daily_price',
            name='eps',
            field=models.FloatField(blank=True, help_text='EPS', null=True),
        ),
        migrations.AddField(
            model_name='daily_price',
            name='pbr',
            field=models.FloatField(blank=True, help_text='PBR', null=True),
        ),
        migrations.AddField(
            model_name='daily_price',
            name='per',
            field=models.FloatField(blank=True, help_text='PER', null=True),
        ),
    ]
