# Generated by Django 3.2.8 on 2021-11-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0006_fs_lob_gpa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily_price',
            options={'ordering': ['date'], 'verbose_name': '주가', 'verbose_name_plural': '주가'},
        ),
        migrations.AlterModelOptions(
            name='fs_account',
            options={'ordering': ['account_name'], 'verbose_name': '계정명', 'verbose_name_plural': '계정명'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['bs_year'], 'verbose_name': '연도별 데이터', 'verbose_name_plural': '연도별 데이터'},
        ),
        migrations.RemoveField(
            model_name='daily_price',
            name='market_gap',
        ),
        migrations.AddField(
            model_name='daily_price',
            name='market_cap',
            field=models.FloatField(blank=True, help_text='시가총액', null=True),
        ),
    ]
