# Generated by Django 3.2 on 2021-07-31 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBmanageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fs_account',
            name='fs_div',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_account', to='DBmanageapp.fs_div'),
        ),
    ]
