# Generated by Django 3.2 on 2021-08-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBmanageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fs_lob',
            name='exist',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
